---
- name: Deploy Wisecow App
  hosts: web
  become: true
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Run Wisecow container
      community.docker.docker_container:
        name: wisecow
        image: 741957640939.dkr.ecr.ap-south-1.amazonaws.com/wisecow:latest
        state: started
        restart_policy: always
        published_ports:
          - "5000:5000"
